[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
auto_detect_solc = true
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
ignored_paths = [
  "contracts/wildcard.sol",
  "contracts/libraries/Operator.sol",
  "contracts/interfaces/Operator.sol",
  "contracts/interfaces/ShareWrapper.sol"
]